#!/bin/bash

SBF=../../../../target/sbf-solana-solana/release/spl_token_2022.so
INLINE_CFG=cvt_inlining.txt
SUMMARY_CFG=cvt_summaries.txt

if [ $# -lt 1 ];  then
    echo "Usage: $0 SBF_FILE"
    exit 1
fi

RULE=$1
EXTRA_OPTS=${@:2}
PROVER_ARGS="-solanaOptimisticSlicerIgnoresStackWidths true -solanaOptimisticJoin true -solanaOptimisticOverlaps true -solanaInlining $INLINE_CFG -solanaSummaries $SUMMARY_CFG -solanaEntrypoint $RULE $EXTRA_OPTS"

certoraRun.py $SBF \
	      --prover_args "${PROVER_ARGS}" \
	      --prover_version jorge/solana-dev --server staging --debug
