#!/bin/bash

RULE=$1
EXTRA_OPTS=${@:2}
java -ea -Xmx8g -Dtopic.spec -Dlevel.ebpf=info  -Dverbose.times -Dcvt.simple.parallel -Djava.awt.headless=true -jar /Users/jorge/Repos/Certora_EVMVerifier/Builds/emv.jar -deleteSMTFile false -graphDrawLimit 2000 ../../../../target/sbf-solana-solana/release/spl_token_2022.so  -solanaInlining ../certora/cvt_inlining.txt -solanaSummaries ../certora/cvt_summaries.txt  -solanaOptimisticSlicerIgnoresStackWidths true -solanaEntrypoint $RULE $EXTRA_OPTS 
